# Opinion Mining Tools Benchmarking

In this notebook we display the results of our benchmarking of several opinion mining tools

## Sentiment

In [18]:
import pandas as pd
import glob

results_files = glob.glob("results/en-sentiment-*.csv")


results_dfs = []

for lang in ["en", "es", "it"]:
    results_files = glob.glob(f"results/{lang}-sentiment-*.csv")

    dfs = []
    for file in results_files:
        dfs.append(pd.read_csv(file))

    df = pd.concat(dfs, ignore_index=True)

    # Drop Macro Precision and Recall
    df = df.drop(columns=['Macro Precision', 'Macro Recall'])

    results = df.pivot(index="Dataset", columns="Model", values="Macro F1")

    results["lang"] = lang

    results_dfs.append(results.reset_index())


results = pd.concat(results_dfs)

results.set_index(["lang", "Dataset"], inplace=True)

res = (results * 100).round(1)[["pysentimiento", "tweetnlp", "stanza", "flair", "textblob", "vader"]]


res.fillna("-").astype(str)

Model                     pysentimiento tweetnlp stanza flair textblob vader
lang Dataset
en   amazon                        63.2     60.7   52.9     -     45.0  19.0
     financial_phrasebank          68.2     58.8   44.1     -     44.9  25.1
     mteb                          75.7     75.5   51.9     -     47.4  20.3
     sent_eval                     88.3     81.3   77.4  85.1     67.8  73.0
     sentiment140                  85.8     86.7   68.5     -     63.3  26.0
     sst2                          87.9     79.7   85.0  93.6     65.9  66.8
es   amazon                        61.8     21.5   48.5     -        -     -
     mteb                          76.8     31.6   60.1     -        -     -
it   feel_it                       88.2     61.6      -     -        -     -

## Hate Speech

In [21]:
import pandas as pd
import glob


results_dfs = []

for lang in ["en", "es", "it"]:
    results_files = glob.glob(f"results/{lang}-hate_speech-*.csv")

    dfs = []
    for file in results_files:
        dfs.append(pd.read_csv(file))

    df = pd.concat(dfs, ignore_index=True)

    # Drop Macro Precision and Recall
    df = df.drop(columns=['Macro Precision', 'Macro Recall'])

    results = df.pivot(index="Dataset", columns="Model", values="Macro F1")

    results["lang"] = lang

    results_dfs.append(results.reset_index())


results = pd.concat(results_dfs)

results.set_index(["lang", "Dataset"], inplace=True)

res = (results * 100).round(1)[["pysentimiento", "tweetnlp"]]


res.fillna("-").astype(str)

Model          pysentimiento tweetnlp
lang Dataset
en   hatecheck          52.1     68.6
es   hatecheck          66.7     26.1
it   hatecheck          53.1     25.4